name: entry-server CD

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: minx-prod
  PROJECT_NUMBER: 329382624121
  REGION: asia-northeast1
  APP_NAME: entry-server

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions-pool/providers/github"
          service_account: "github-actions@${{ env.PROJECT_ID }}.iam.gserviceaccount.com"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
      - name: Configure Docker
        run: |
          ARTIFACT_REGISTRY_HOST=${REGION}-docker.pkg.dev
          IMAGE_NAME=${PROJECT_ID}/${APP_NAME}/base:latest
          gcloud auth configure-docker ${REGION}-docker.pkg.dev
      - name: "Build and push Docker image"
        run: |
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME 
        working-directory: ${{ env.APP_NAME }}
      - name: "Deploy to Cloud Run"
        run: |
          gcloud run deploy $APP_NAME \
            --image $IMAGE_NAME \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated
